### ISSUE TITLE
Allow lists in registry posts

### ISSUE THREAD

**Issue by abettermap** [CodeForFoco/codeforfoco.github.io#103]
Jekyll ain't having it: https://github.com/CodeForFoco/codeforfoco.github.io/pull/101#issue-238023331

**Comment by abettermap** [comment]
@deidyomega 

Ok how's this look?

![screen shot 2017-06-24 at 8 53 50 pm](https://user-images.githubusercontent.com/4974087/27513460-b8c4ccbe-5923-11e7-81c7-953a98a40288.jpg)

The `<ul>` items were definitely present already in the template, but the site-wide `<ul>` styling was a little nuclear. Feel free to mess with [that branch](https://github.com/CodeForFoco/codeforfoco.github.io/tree/103.registry-lists) if you want, otherwise I'm going to pull it in.

FYI I still can't see your post (the screenshot is from pasting your markdown into someone else's post). Can't figure it out and it's kinda driving me nuts haha, so let me know if you have any ideas.

**Comment by abettermap** [comment]
Got it: the date! Your registry post date was July and for whatever reason, Jekyll would not render a future date. Talk about a tricky one to troubleshoot haha

**Comment by deidyomega** [comment]
Whoops... Good catch... Looks good from here.  Sorry for the trouble!

**Comment by deidyomega** [comment]
As I can't get that branch to load (liquid issues), there's no way for me to test it.  But your screenshot works for me.

**Comment by abettermap** [comment]
All set now, `master` has the liquid update.
