### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by abettermap** [CodeForFoco/codeforfoco.github.io#111]
Not a mega concern, but it would be nice to show up in first page of Google results for searches like `fort collins volunteer coding`. I got to page 6 and still didn't see the site using that criteria.

Not an expert, but things that help SEO:
1. Good site architecture (well-structured site outline, internal links, URL stuff, etc.)
1. Keywords within content
1. Meta- titles, meta tags
1. ???

**Comment by JordanMajd** [comment]
Completing #38 Should also help improve SEO.

**Comment by abettermap** [comment]
I don't know if it's a fact but I have heard that Google favors secure sites. Looks like we can get https for free:  https://css-tricks.com/switching-site-https-shoestring-budget/

Either way, SSL is never a bad idea, especially if we implement a project idea form directly in the site.

**Comment by abettermap** [comment]
Same goes for Solar Scorecard as well.

**Comment by davidbhayes** [comment]
I think we need to get some SEO expert to give us a guide. But I think getting listed on brigade.codeforamerica.org will help. I started that...

**Comment by davidbhayes** [comment]
Closing as a bit unfocused and a far-less-urgent problem now 🤓
