### ISSUE TITLE
Add minutes section and template

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/codeforfoco.github.io#114]
- [ ] Migrate minutes from Google docs to our website
- [ ] Create a template file for minutes for that post directory.
- [ ] Add minutes to website chart, see #91. 

Google forms are painful to use, limit collaboration, who can view, edit and take minutes.

Github and git allows for people to collaborate on minutes. Project leaders can fill in the minutes for their current project. It enables anybody to edit, modify, create and take minutes. We can use markdown to format and take minutes and SASS to style them.

**Comment by davidbhayes** [comment]
Believe this is done. If you follow the link in the footer of the site, you'll be taken to the minutes page and the new procedure for taking minutes. I wasn't sure exactly what if anything I needed to do re: #91, but I didn't add a link to the header as I think @JordanMajd and I didn't think it merited it and weren't quite how to use @abettermap's chart, if it affected what we do with respect to linking this.

**Comment by abettermap** [comment]
I forgot to include minutes in the chart until later, hadn't thought too hard about where to fit it in, but what you've done works great for now. Re-structuring the site to match the chart will take a bit more thought anyway.
