### ISSUE TITLE
Improve home page and nav responsiveness

### ISSUE THREAD

**Issue by abettermap** [CodeForFoco/codeforfoco.github.io#124]
The title was pretty snug at certain screen sizes even with `FoCo` abbreviated, and much more so now with it spelled out in full:

![image](https://user-images.githubusercontent.com/4974087/28757613-e9afe570-7543-11e7-9d50-167c087403d6.png)

Just need to drop the font size and line-height down a bit on a breakpoint or two.

**Comment by abettermap** [comment]
Several things are truncated or not looking great on tablet-ish:

![image](https://user-images.githubusercontent.com/4974087/30244412-a9a6c2ee-957a-11e7-87b1-14f460b26734.png)

**Comment by davidbhayes** [comment]
Closing as I no longer see the issue here 🤓
