### ISSUE TITLE
Investigate build issues.

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/codeforfoco.github.io#132]
Builds worked fine up until the merge of last week's minutes. We reverted to the last built commit and the repository still won't build.

**Comment by abettermap** [comment]
The important part of GH's response to David's support request:

> Here's the full error we're seeing on our side:
> 
> ```
> Liquid Exception: no implicit conversion of Integer into String in /_layouts/default.html
>             Fatal: TypeError
>                    no implicit conversion of Integer into String
> ```
> It looks like the cause of this is a bug in Jekyll, the fix for which is quite new, and has yet to be incorporated into GitHub Pages:
> 
> https://github.com/jekyll/jekyll/pull/6281
>
> While we're working on fixing that, you should be able to resolve this error by changing the value of title: in your 404.html file:
> 
> https://github.com/CodeForFoco/codeforfoco.github.io/blob/master/404.html#L3
> 
> Can you try updating that to be a string, such as "404" instead of 404?

**Comment by abettermap** [comment]
I made the change. I'll leave this open for a sec until we know if build worked.

**Comment by abettermap** [comment]
Happy green checkmark so i'm calling it good:

![image](https://user-images.githubusercontent.com/4974087/29244464-63e5dd78-7f75-11e7-9454-5761e52e05dc.png)

**Comment by abettermap** [comment]
Ok did some minor triage and pushed things up. I think we have all the commits we need again but i'll hang on to my backup branch for a bit. Build succeeded after push, but holler if any problems.
