### ISSUE TITLE
Blog Posts Don't Appear on the Blog

### ISSUE THREAD

**Issue by davidbhayes** [CodeForFoco/codeforfoco.github.io#154]
**What I want to have happen:**

Anything put in the /_posts/blog directory shows up on the page of the site labelled "blog"

**Misbehavior I'm seeing:**

I've got two posts https://github.com/CodeForFoco/codeforfoco.github.io/blob/master/_posts/blog/2019-10-03-fcx-version-1.md (for example) which aren't on the blog

**What I think the causes/problem is**

We're weirdly linking on the site to "blog" category page (I think, for lack of better terminology). I don't believe I've given the posts that aren't appearing the blog "tag" or "category." I think we probably want to repoint at something that is meant to show *anything* in that directory. I'm just not totally certain how to do that.

**Comment by schillingjerrid** [comment]
I'll take this issue

**Comment by davidbhayes** [comment]
Thanks @schillingjerrid! :)
