### ISSUE TITLE
Slack Invite Automation

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/codeforfoco.github.io#16]
One of the first iterations of the site had an input for slack invites. Let's add it back in.

**Comment by englehorn** [comment]
I added the slack invite on the onboarding page 

https://github.com/CodeForFoco/org/blob/master/onboarding.md

@idcrook

**Comment by idcrook** [comment]
thanks for add this to the github.  I'll try to get updated onto the site tomorrow

**Comment by idcrook** [comment]
have a clone that points Slack button to signup heroku. PR TBD.

**Comment by idcrook** [comment]
fixed in #26
