### ISSUE TITLE
Image sizing

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/codeforfoco.github.io#17]
A lot of the images are stretched or displayed at too large of a size for their resolution.

**Comment by JordanMajd** [comment]
Images are not rendered at their exact aspect ratio in several areas.

One such example would be the header image for a post / page as seen
[here](http://codeforfoco.org/code-of-conduct/).

Another example of this would be the preview image for a post on the pages they are listed, as seen [here](http://codeforfoco.org/category/partners/).

Thanks

**Comment by JordanMajd** [comment]
See #58 and #50

**Comment by abettermap** [comment]
Added `workflow` label in the hopes that we can automate image optimization somehow.
