### ISSUE TITLE
Create list of tasks for beginners to get started on

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/codeforfoco.github.io#20]
Add and label a lot of tiny tasks for onboarders to start editing.

**Comment by idcrook** [comment]
Could there be a Label added corresponding to those as well?

Here is the current list of  Labels
![screenshot 2016-12-15 10 39 19](https://cloud.githubusercontent.com/assets/461806/21235135/c75daf82-c2b2-11e6-81ba-89506662b4d6.png)

**Comment by JordanMajd** [comment]
Absolutely!

**Comment by itorain** [comment]
What else needs to be done for this?

**Comment by JordanMajd** [comment]
Looks like we have plenty of tasks. If you think of anything else that needs added then be sure to create an issue and tag it.
