### ISSUE TITLE
Use only GitHub supported plugins for jekyll

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/codeforfoco.github.io#22]
Use only github supported plugins so that it is easier for beginners to get started.

This way they dont need to install jekyll, ruby and bundler.

**Comment by idcrook** [comment]
I plan on testing local and github builds. `_config.yml` and `Gemfile` looked relatively vanilla to me.

Also, can't edit this issue title @JordanMajd so could I get permissions to this repo?

**Comment by idcrook** [comment]
@JordanMajd #24 can be merged

**Comment by idcrook** [comment]
I released my updates around the `jekyll` config. The site appears to be live with my changes, and things still look like they are working. 😺
