### ISSUE TITLE
Add Donations Page

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/codeforfoco.github.io#35]
Add a page with information on why and how to donate.

**Comment by abettermap** [comment]
@JordanMajd I split this out into two issues. 

Donations button currently links directly to the Code For America site. Are you thinking of having an intermediate landing page in between to explain why/how to donate, or are we just going to run with the direct link?

**Comment by JordanMajd** [comment]
The donation button looks great, but I think having an intermediate page might be useful as well.

**Comment by abettermap** [comment]
Agreed. Like we have with FCBC. Nice to be coaxed into something with an explanation rather than click >> GIVE US MONEY

**Comment by DanLaRoche** [comment]
Proposed text for donate page:
[donateplease.docx](https://github.com/CodeForFoco/codeforfoco.github.io/files/782000/donateplease.docx)

**Comment by abettermap** [comment]
That looks good. I'll make some tweaks and bring it into a page.

**Comment by abettermap** [comment]
My mistake, looks like it's already in https://github.com/CodeForFoco/codeforfoco.github.io/blob/master/_posts/organization/2017-02-16-donate.md
