### ISSUE TITLE
Update description of Code for Fort Collins

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/codeforfoco.github.io#38]
The current description is nebulous. It does not describe who we are and what we do. We should update the site to have a better description.

**Comment by JordanMajd** [comment]
Updating our description should help with SEO #111

**Comment by davidbhayes** [comment]
I've changed `index.html` and `_config.yml` (this commit is above) to be a little more concise and clear. Here's the version I quit with:

>  Code for Fort Collins is a volunteer organization dedicated to using technology to solve challenges that charities, government agencies, and other groups in the city face.

> We are community members who want to have a positive impact on Fort Collins. By finding problems, refining solutions, and building them out, we grow professionally and learn new technical skills. 

Feedback/tweaks welcome from @JordanMajd @abettermap and anyone else interested.

**Comment by abettermap** [comment]
Looks good. How about this for first paragraph?

_Code for Fort Collins is a volunteer organization who develops technology-driven solutions to challenges faced by charities, government agencies, and other groups within the city._
