### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/codeforfoco.github.io#4]
- On any screen resolution there is about 20 pixels of horizontal scroll
- There is about 20 pixels of whitespace right of the website

Confirmed on both Firefox and Chrome.

**Comment by J-Roel** [comment]
Fixed width issue and prevented x axis scrolling. [ab457b](https://github.com/CodeForFoco/codeforfoco.github.io/commit/ab4574b18c0f974f58411102ff3496cb84901c8c) Confirmed working correctly on Chrome, Firefox, Safari and on iPhone 6.

**Comment by JordanMajd** [comment]
Awesome!

Thanks
