### ISSUE TITLE
Add Sponsor Page

### ISSUE THREAD

**Issue by abettermap** [CodeForFoco/codeforfoco.github.io#47]
Add a page with information on different sponsorship opportunities (formerly part of #35)

**Comment by JordanMajd** [comment]
Should have a paragraph which summarizes what we provide in return for sponsorship and how to get in touch.

**Comment by davidbhayes** [comment]
Closing as misaligned with current priorities. (Our meeting space is covered by the library, and random donation drives have covered most of our on-going operational costs/desires.)
