### ISSUE TITLE
Flow of partners logo out of whack

### ISSUE THREAD

**Issue by DanLaRoche** [CodeForFoco/codeforfoco.github.io#58]
Main page partners logos flow weirdly on 1366 x 768 screen (actually 1080p with 150% dpi scale on windows). I think we should resize to fit at least 3 logos side to side when viewed with such a standard page size as ~720p.

**Comment by abettermap** [comment]
@DanLaRoche  

I made a bunch of changes recently and may have fixed this indirectly. If it looks OK in the website now, we can close this. 

I also grabbed the actual Mesh logo from their Facebook page, so if that's OK then we can use that instead of the placeholder you created.

**Comment by abettermap** [comment]
Closed by one of the 75 commits in #67 😮
