### ISSUE TITLE
Standardize code syntax

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/codeforfoco.github.io#59]
Add a dotfile that tells all editors to style the code the same and use the same line endings so that beautifies don't bleep everything up. 

EDIT (Jason): let's include a few things:
- ~~editorconfig~~ added in https://github.com/CodeForFoco/codeforfoco.github.io/commit/0104d7eb805216b55029cf68793fbb8c92a5aed4
- ~~csscomb~~ added in https://github.com/CodeForFoco/codeforfoco.github.io/commit/4d0fce5c0e680f8cb8dfe13cf7ac204556d37fe1
- jsbeautifyrc (already in this branch: https://github.com/CodeForFoco/codeforfoco.github.io/tree/code-standards)

**Comment by abettermap** [comment]
@JordanMajd we actually already had an `.editorconfig` but no instructions about it so I added some links in README along with `.csscomb.json` and `.jsbeautifyrc` files. Have a skim in [this branch](https://github.com/CodeForFoco/codeforfoco.github.io/tree/code-standards) if you get a chance and let me know if that approach and the **Code Standards** section are the right direction to take.

I think the linter installation is a little overwhelming and I've had challenges with it in the past on both Atom and Sublime (not the linter itself, just the individual language-specific plugins). There's a lot going on for new users, so I don't know if we should keep everything optional or what. Kinda defeats the purpose that way, but is less intimidating for beginners. What do you think? 

Also, how do you feel about moving linter/beautifier stuff into [CONTRIBUTING.md](https://github.com/CodeForFoco/org/blob/master/CONTRIBUTING.md) at the org repo? Then we could link to it for each project and just include the required language-specific requirements on a per-project basis (Bike Co-op has PHP, for example).

**Comment by abettermap** [comment]
@JordanMajd Yo. It's been a fortnight, friend-o. 😉  Shoot me a response when you get a chance to read my last comment.

**Comment by abettermap** [comment]
Added `csscomb` in https://github.com/CodeForFoco/codeforfoco.github.io/commit/4d0fce5c0e680f8cb8dfe13cf7ac204556d37fe1
