### ISSUE TITLE
Idea submission form -- front end 

### ISSUE THREAD

**Issue by abettermap** [CodeForFoco/codeforfoco.github.io#68]
The front half of #36 

### Required Fields
- name
- email
- idea summary/title (will become title of GH issue)
- idea description (will become body of GH issue)

### Also Need
- note/disclaimer indicating that submitter will be contacted

**Comment by abettermap** [comment]
Here's a start: 

https://github.com/CodeForFoco/codeforfoco.github.io/commit/8b32e5315e63c2e0fbc5eee2557f2dce66bc0a8e

**Comment by davidbhayes** [comment]
Closing as old and not particularly effective as a way to find useful projects (given our current level of renown and scale)
