### ISSUE TITLE
Allow Tags in Projects

### ISSUE THREAD

**Issue by redisforlosers** [CodeForFoco/codeforfoco.github.io#86]
i.e. programming languages or technologies used, the industry the project serves (government, transportation, non profit, etc).

**Comment by JordanMajd** [comment]
Add tags to projects on github or on our website?

If on github, perhaps this issue should be moved to the org repo.

**Comment by abettermap** [comment]
We were thinking website but GH tags would be good too (looks like some have been added for several projects). 

Super low priority I think, more pressing issues first, so maybe backburner for now.

**Comment by abettermap** [comment]
Having fun playing around with this Jekyll business, it's really flexible. 

![img_0693](https://cloud.githubusercontent.com/assets/4974087/26291972/a257504c-3e6f-11e7-9b7b-259e21b029bb.PNG)

If we wanted to go even more meta, could consolidate unique tag values across all project pages and members posts, then into a table:

![img_0691](https://cloud.githubusercontent.com/assets/4974087/26292002/dac2eefa-3e6f-11e7-8ef5-6b883c677b28.PNG)

All comes from a project template and front matter in the markdown: https://github.com/CodeForFoco/codeforfoco.github.io/commit/6790fe16870f93625ab9e02c9ccea915e23de165

Much to hone, but it's coming along.
