### ISSUE TITLE
Create Completed Projects Page

### ISSUE THREAD

**Issue by redisforlosers** [CodeForFoco/codeforfoco.github.io#87]

**Comment by JordanMajd** [comment]
Do we need to differentiate completed and in progress projects? Or can this and #88 be merged?

**Comment by abettermap** [comment]
Maybe they don't need to necessarily be different pages/templates, but it would be nice to  differentiate them by status somehow so we could display them that way in the portfolio. 

Open to suggestions though. Thoughts?

**Comment by abettermap** [comment]
Closing this as #88 is close enough and #96 will likely include some meta about completion date.
