### ISSUE TITLE
Link to GitHub Issues / Ideas

### ISSUE THREAD

**Issue by redisforlosers** [CodeForFoco/codeforfoco.github.io#89]

**Comment by abettermap** [comment]
If we tag all of our ideas with `Project Idea`, we can link directly to the whole list pretty easily: https://github.com/CodeForFoco/org/issues?q=is%3Aissue+is%3Aopen+label%3A%22Project+Idea%22

**Comment by redisforlosers** [comment]
great idea!

**Comment by davidbhayes** [comment]
I don't think we're really seeking to receive project ideas this way any more, so I'll close this. Though it does remind me that we should publicly document *how* we're now looking to receive new project ideas. 🤓
