### ISSUE TITLE
Create project page template 

### ISSUE THREAD

**Issue by abettermap** [CodeForFoco/codeforfoco.github.io#96]
Suggested:

---
layout: post
title:  "project title"
date:   2017-05-12 12:00:00 -0700
image: projects/project-image.svg
categories: projects
status: in-progress or complete
tech-tags: php, wordpress, website, app, responsive, etc. 
industry-tags: transportation, recycling, crime, whatever 
---

## Customer description 
Who they are, what they do. 

## Project summary 
What we did/are doing.  

## Nerd specs
We are a coding org, what are the tech details?
- Hosting 
- Languages/platforms 
- Other nerdery

**Comment by abettermap** [comment]
Good start for Bike Co-op, can base the template off that: https://github.com/CodeForFoco/codeforfoco.github.io/commit/6790fe16870f93625ab9e02c9ccea915e23de165

**Comment by JordanMajd** [comment]
Looks pretty solid overall.

Customer description may not be necessary as not all projects will have customers. We could either include that info in the project summary or just have it be an optional field.
